############################################################
# +------------------------------------------------------+ #
# |                       Config                         | #
# +------------------------------------------------------+ #
############################################################

# Shows additional messages in console.
debug: false

# Whether the plugin is enabled.
# Reload command is always enabled.
enabled: true

# Sound played to the losing player.
# Sounds: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
loss-sound: 'ENTITY_VILLAGER_NO'
loss-volume: 1
loss-pitch: 1

# Sound played when rolling.
# Sounds: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
roll-sound: 'ENTITY_PLAYER_LEVELUP'
roll-volume: 1
roll-pitch: 1